#!/usr/bin/env node

/**
 * TypeScript Type Generator
 * 
 * Generates TypeScript interfaces from JSON schemas.
 * Outputs to /src/types/generated/tool-types.ts
 * 
 * Usage:
 *   pnpm tsx scripts/generate-tool-types.ts
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

const OUTPUT_PATH = join(process.cwd(), 'src', 'types', 'generated', 'tool-types.ts');

interface JsonSchema {
  type?: string;
  properties?: Record<string, JsonSchemaProperty>;
  required?: string[];
  description?: string;
}

interface JsonSchemaProperty {
  type?: string;
  description?: string;
  enum?: unknown[];
  items?: JsonSchemaProperty;
  properties?: Record<string, JsonSchemaProperty>;
  $ref?: string;
}

function jsonTypeToTs(type: string | undefined, property?: JsonSchemaProperty): string {
  if (!type) return 'unknown';
  
  switch (type) {
    case 'string':
      if (property?.enum) {
        return property.enum.map(v => `'${String(v)}'`).join(' | ');
      }
      return 'string';
    
    case 'number':
    case 'integer':
      return 'number';
    
    case 'boolean':
      return 'boolean';
    
    case 'array':
      if (property?.items) {
        const itemType = jsonTypeToTs(property.items.type, property.items);
        return `${itemType}[]`;
      }
      return 'unknown[]';
    
    case 'object':
      if (property?.properties) {
        const nested = generateInterfaceFromSchema({ type: 'object', properties: property.properties }, 'NestedObject');
        return nested.replace(/export interface \w+ /, '').trim();
      }
      return 'Record<string, unknown>';
    
    default:
      return 'unknown';
  }
}

function generateInterfaceFromSchema(schema: JsonSchema, name: string): string {
  if (!schema.properties) {
    return `export type ${name} = ${jsonTypeToTs(schema.type)};`;
  }

  const lines: string[] = [
    `/**`,
    ` * ${schema.description || `Generated type for ${name}`}`,
    ` */`,
    `export interface ${name} {`,
  ];

  Object.entries(schema.properties).forEach(([key, prop]) => {
    const isRequired = schema.required?.includes(key);
    const tsType = jsonTypeToTs(prop.type, prop);
    const optional = isRequired ? '' : '?';
    
    lines.push(`  /**`);
    lines.push(`   * ${prop.description || `${key} field`}`);
    lines.push(`   */`);
    lines.push(`  ${key}${optional}: ${tsType};`);
  });

  lines.push('}');

  return lines.join('\n');
}

async function generateToolTypes() {
  console.log('🔧 Generating TypeScript types from tool schemas...');
  
  try {
    // Fetch schemas from API
    const response = await fetch('http://localhost:3001/api/sap/tools/schemas');
    
    if (!response.ok) {
      throw new Error(`Failed to fetch schemas: ${response.statusText}`);
    }

    const data = await response.json();
    
    // We need tool names from the tools API
    const toolsResponse = await fetch('http://localhost:3001/api/sap/tools');
    const toolsData = await toolsResponse.json();
    
    const typeFiles: string[] = [
      '/**',
      ' * Auto-generated TypeScript types from on-chain tool schemas',
      ' * Generated by: scripts/generate-tool-types.ts',
      ` * Generated at: ${new Date().toISOString()}`,
      ' */',
      '',
      '// eslint-disable-next-line @typescript-eslint/no-explicit-any',
    ];

    // Generate interface for each tool
    data.schemas.forEach((schema: any, idx: number) => {
      const tool = toolsData.tools.find((t: any) => t.pda === schema.toolPda);
      const toolName = tool?.descriptor?.toolName || `Tool_${idx}`;
      const safeName = toolName.replace(/[^a-zA-Z0-9]/g, '_');
      
      const tsInterface = generateInterfaceFromSchema(
        schema.schemaJson as JsonSchema,
        `${safeName}Params`
      );
      
      typeFiles.push('');
      typeFiles.push(tsInterface);
      typeFiles.push('');
    });

    // Add helper types
    typeFiles.push(`
/**
 * Generic tool execution request
 */
export interface ToolExecutionRequest<T = Record<string, unknown>> {
  toolPda: string;
  params: T;
  apiKey?: string;
}

/**
 * Generic tool execution response
 */
export interface ToolExecutionResponse<T = unknown> {
  success: boolean;
  result?: T;
  signature?: string;
  error?: string;
}

/**
 * Map of tool PDA to generated types
 */
export type ToolTypeMap = {
${data.schemas.map((s: any, i: number) => {
  const tool = toolsData.tools.find((t: any) => t.pda === s.toolPda);
  const name = tool?.descriptor?.toolName || `Tool_${i}`;
  const safeName = name.replace(/[^a-zA-Z0-9]/g, '_');
  return `  '${s.toolPda}': ${safeName}Params;`;
}).join('\n')}
};
`);

    // Ensure output directory exists
    const dir = join(OUTPUT_PATH, '..');
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }

    // Write types file
    writeFileSync(OUTPUT_PATH, typeFiles.join('\n'));

    console.log(`✅ TypeScript types generated successfully!`);
    console.log(`📄 Output: ${OUTPUT_PATH}`);
    console.log(`📊 Types generated: ${data.schemas.length}`);
    console.log('');
    console.log('📝 Usage:');
    console.log(`   import type { ToolTypeMap } from '~/types/generated/tool-types';`);
    console.log(`   type MyToolParams = ToolTypeMap['tool-pda-here'];`);
    
    return typeFiles.join('\n');
  } catch (error) {
    console.error('❌ Type generation failed:', error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

// Run if executed directly
if (require.main === module) {
  generateToolTypes();
}

export { generateInterfaceFromSchema, generateToolTypes };
